import type { Manual } from "@/core/types";
import index from "@/generated/manuals.index.json";

/** The manual library, generated by `pnpm manuals:index` (runs before dev/build/test). */
export const MANUALS = index as unknown as Manual[];

export function getManual(id: string): Manual | undefined {
  return MANUALS.find((m) => m.id === id);
}
